update deploy argocd

diff --git a/azure-pipeline.yml b/azure-pipeline.yml
--- a/azure-pipeline.yml
+++ b/azure-pipeline.yml
@@ -62,12 +62,27 @@ steps:
     scriptType: 'bash'
     scriptLocation: 'inlineScript'
     inlineScript: |
+      rm -rf HelmMonolithic
       git clone https://github.com/KhacThien88/HelmMonolithic
       cd HelmMonolithic
       sudo cp ~/argocd/deploy_be.sh .
       sudo cp ~/argocd/uninstall.sh .
       ./deploy.sh
       kubectl get pods -n todoapp-test
+
+- task: AzureCLI@2
+  displayName: 'Deploy to ArgoCD'
+  inputs:
+    azureSubscription: '$(azureSubscription)'
+    scriptType: 'bash'
+    scriptLocation: 'inlineScript'
+    inlineScript: |
+      cd Charts/argocd/dev
+      kubectl apply -f backend-server.yml
+      kubectl apply -f frontend-server.yml
+      cd ../staging
+      kubectl apply -f backend-server.yml
+      kubectl apply -f frontend-server.yml
 
 - task: AzureCLI@2
   displayName: 'Health Check API using GET /tasks'
@@ -89,7 +104,7 @@ steps:
         echo "Checking health of API at $API_URL"
         for ((i=1; i<=$RETRY_COUNT; i++)); do
           echo "Attempt $i of $RETRY_COUNT"
-          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout $TIMEOUT --insecure "$API_URL" || echo "000")
+          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout $TIMEOUT --insecure "$API_URL" || echo "Can't get status")
           
           if [ "$HTTP_STATUS" == "$EXPECTED_STATUS" ]; then
             echo "Health check passed: Received HTTP $HTTP_STATUS"
